CREATE TABLE IF NOT EXISTS quotations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quotation_number VARCHAR(50) UNIQUE NOT NULL,
  quotation_date DATE NOT NULL,
  valid_until DATE,
  customer_id INT,
  customer_name VARCHAR(200),
  customer_email VARCHAR(150),
  customer_phone VARCHAR(20),
  customer_company VARCHAR(200),
  customer_gstin VARCHAR(20),
  billing_address TEXT,
  subtotal DECIMAL(15,2) DEFAULT 0,
  discount DECIMAL(15,2) DEFAULT 0,
  cgst DECIMAL(15,2) DEFAULT 0,
  sgst DECIMAL(15,2) DEFAULT 0,
  igst DECIMAL(15,2) DEFAULT 0,
  total_tax DECIMAL(15,2) DEFAULT 0,
  shipping_estimate DECIMAL(15,2) DEFAULT 0,
  total DECIMAL(15,2) DEFAULT 0,
  notes TEXT,
  terms TEXT,
  internal_notes TEXT,
  status ENUM('draft','sent','accepted','rejected','expired') DEFAULT 'draft',
  remark TEXT,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotation_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quotation_id INT NOT NULL,
  product_name VARCHAR(500) NOT NULL,
  description TEXT,
  size VARCHAR(100),
  quantity INT NOT NULL,
  unit VARCHAR(50),
  unit_price DECIMAL(15,2) NOT NULL,
  discount_percent DECIMAL(5,2) DEFAULT 0,
  gst_percent DECIMAL(5,2) DEFAULT 0,
  cgst_amount DECIMAL(15,2) DEFAULT 0,
  sgst_amount DECIMAL(15,2) DEFAULT 0,
  igst_amount DECIMAL(15,2) DEFAULT 0,
  total DECIMAL(15,2) NOT NULL,
  FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS digital_invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_number VARCHAR(50) UNIQUE NOT NULL,
  invoice_date DATE NOT NULL,
  due_date DATE,
  customer_id INT,
  customer_name VARCHAR(200) NOT NULL,
  customer_email VARCHAR(150) NOT NULL,
  customer_phone VARCHAR(20),
  customer_gstin VARCHAR(20),
  billing_address TEXT,
  delivery_method VARCHAR(100),
  download_link TEXT,
  download_password VARCHAR(100),
  link_expiry DATE,
  download_limit INT DEFAULT 5,
  file_size VARCHAR(50),
  version_number VARCHAR(50),
  subtotal DECIMAL(15,2) DEFAULT 0,
  discount DECIMAL(15,2) DEFAULT 0,
  cgst DECIMAL(15,2) DEFAULT 0,
  sgst DECIMAL(15,2) DEFAULT 0,
  igst DECIMAL(15,2) DEFAULT 0,
  total_tax DECIMAL(15,2) DEFAULT 0,
  total DECIMAL(15,2) DEFAULT 0,
  paid_amount DECIMAL(15,2) DEFAULT 0,
  payment_mode VARCHAR(50),
  payment_status ENUM('paid','partial','unpaid','draft') DEFAULT 'unpaid',
  notes TEXT,
  internal_notes TEXT,
  status ENUM('draft','sent','paid','delivered','cancelled') DEFAULT 'draft',
  remark TEXT,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS digital_invoice_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  digital_invoice_id INT NOT NULL,
  product_name VARCHAR(500) NOT NULL,
  item_type VARCHAR(100),
  description TEXT,
  file_format VARCHAR(100),
  license_type VARCHAR(100),
  quantity INT DEFAULT 1,
  unit VARCHAR(50),
  unit_price DECIMAL(15,2) NOT NULL,
  discount_percent DECIMAL(5,2) DEFAULT 0,
  gst_percent DECIMAL(5,2) DEFAULT 18,
  cgst_amount DECIMAL(15,2) DEFAULT 0,
  sgst_amount DECIMAL(15,2) DEFAULT 0,
  igst_amount DECIMAL(15,2) DEFAULT 0,
  total DECIMAL(15,2) NOT NULL,
  FOREIGN KEY (digital_invoice_id) REFERENCES digital_invoices(id) ON DELETE CASCADE
);
